name: laundrymart
description: A new Flutter project.

publish_to: "none"

version: 1.3.0+5

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  logger: ^2.0.2+1
  dio: ^5.3.3
  pretty_dio_logger: ^1.1.1
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  upgrader: ^8.2.0
  flutter_riverpod: ^2.1.3
  page_transition: ^2.0.9
  carousel_slider: ^4.1.1
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.7
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  flutter_google_places: ^0.3.0
  location: ^5.0.3
  pin_code_fields: ^8.0.1
  flutter_html: ^3.0.0-alpha.6
  google_maps_flutter: ^2.2.1
  flutter_pdfview: ^1.2.5
  signature: ^5.3.0
  image_picker: ^1.0.4
  flutter_lints: ^2.0.0
  riverpod: ^2.3.2
  expandable: ^5.0.1
  percent_indicator: ^4.2.3
  timeline_tile: ^2.0.0
  cached_network_image: ^3.3.1
  country_picker: ^2.0.20
  curved_navigation_bar: ^1.0.3
  awesome_snackbar_content: ^0.1.2
  intl: ^0.18.1
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.6
  flutter_launch: ^0.3.0
  rename: ^3.0.1
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.1
  flutter_local_notifications: ^16.1.0
  flutter_launcher_icons: ^0.13.1
  table_calendar: ^3.0.8
  flutter_polyline_points: ^1.0.0
  custom_info_window: ^1.0.1
  # app_settings: ^5.0.0
  permission_handler: ^11.0.0
  open_file: ^3.3.2
  lite_rolling_switch: ^1.0.1
  readmore: ^2.2.0
  device_info_plus: ^9.1.1

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.5

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/png/
    - assets/svgs/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/png/Apps-Logo.png"
flutter_intl:
  enabled: true
